# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/DynamicLinks'
pod 'IGListKit'

target ‘TestTanTao' do
    pod 'Alamofire', '~> 4.7'
end

