# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/DynamicLinks'
pod 'IGListKit'
pod 'MJExtension'
pod 'Selene'
pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'

target ‘TestTanTao' do
end

